[package]
name = "spirit_edit_core"
 
version = "0.14.2" 
edition = "2021"
authors = [ "ethereumdegen" ]
license = "MIT"
 
keywords = ["bevy", "editor"]
categories = ["game-development", "gui", "visualization"]
exclude = ["assets"]

 
 



[dependencies]
 
 bevy = "0.14.0"
bevy_mod_raycast = "0.18.0"

bevy_egui = "0.28"
bevy_mod_picking = "0.20.0" 
 
 bevy_clay_tiles = "0.14.2"

serde = { version = "1", features = ["derive"] }
  

 bevy_common_assets = {version="0.11.0", features= ["ron"]}
 
  
ron = "0.8.1"

rand = "0.8"
 